-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 16:53:20 2024
-- Model: Model of events site    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema events_backend_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema events_backend_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `events_backend_db` DEFAULT CHARACTER SET utf8 ;
USE `events_backend_db` ;

-- -----------------------------------------------------
-- Table `events_backend_db`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `desc_short` VARCHAR(255) NULL,
  `desc` TEXT NULL,
  `year` INT NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `image` VARCHAR(255) NULL,
  `thumbnail` VARCHAR(255) NULL,
  `is_current` TINYINT NULL,
  `location` VARCHAR(255) NULL,
  `place` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`event_id`),
  INDEX `events_created_at_idx` (`created_at` ASC) VISIBLE,
  UNIQUE INDEX `events_year_idx` (`year` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` INT NULL DEFAULT 1,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_idx` (`email` ASC) VISIBLE,
  UNIQUE INDEX `users_name_idx` (`name` ASC) VISIBLE,
  INDEX `users_created_at_idx` (`created_at` ASC) VISIBLE,
  INDEX `users_role_idx` (`role` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `events_backend_db`.`lections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`lections` (
  `lection_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `short_desc` VARCHAR(255) NULL,
  `desc` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `capacity` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`lection_id`),
  INDEX `lections_created_at_idx` (`created_at` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`stages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`stages` (
  `stage_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NULL,
  `max_capacity` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`stage_id`),
  INDEX `stages_title_idx` (`title` ASC) VISIBLE,
  INDEX `stages_created_at_idx` (`created_at` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`schedules` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `fk_schedules_event_id_idx` (`event_id` ASC) VISIBLE,
  INDEX `schedules_created_at_idx` (`created_at` ASC) INVISIBLE,
  CONSTRAINT `fk_schedules_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `events_backend_db`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`speakers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`speakers` (
  `speaker_id` INT NOT NULL AUTO_INCREMENT,
  `titul` VARCHAR(45) NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NULL,
  `company` VARCHAR(255) NULL,
  `occupation` VARCHAR(255) NULL,
  `short_desc` VARCHAR(255) NULL,
  `desc` TEXT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `facebook` VARCHAR(255) NULL,
  `instagram` VARCHAR(255) NULL,
  `linkedin` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `thumbnail` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`speaker_id`),
  UNIQUE INDEX `speakers_email_idx` (`email` ASC) VISIBLE,
  INDEX `speakers_created_at_idx` (`created_at` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`testimonials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`testimonials` (
  `testimonial_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `desc` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `thumbnail` VARCHAR(255) NULL,
  `rating` INT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `position` INT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`testimonial_id`),
  INDEX `fk_testimonials_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_testimonials_event_id_idx` (`event_id` ASC) VISIBLE,
  INDEX `testimonials_position_idx` (`position` ASC) VISIBLE,
  INDEX `testimonials_created_at_idx` (`created_at` ASC) VISIBLE,
  CONSTRAINT `fk_testimonials_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `events_backend_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_testimonials_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `events_backend_db`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`sponsors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`sponsors` (
  `sponsor_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `short_desc` VARCHAR(255) NULL,
  `desc` TEXT NULL,
  `logo` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`sponsor_id`),
  UNIQUE INDEX `sponsors_name_idx` (`name` ASC) VISIBLE,
  INDEX `sponsors_created_at_idx` (`created_at` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`galleries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`galleries` (
  `gallery_id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `short_desc` VARCHAR(255) NULL,
  `desc` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`gallery_id`),
  INDEX `fk_galleries_event_id_idx` (`event_id` ASC) INVISIBLE,
  CONSTRAINT `fk_gallery_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `events_backend_db`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `gallery_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `thumbnail` VARCHAR(255) NOT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `position` INT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`image_id`),
  INDEX `fk_images_gallery_id_idx` (`gallery_id` ASC) VISIBLE,
  INDEX `images_position_idx` (`position` ASC) VISIBLE,
  INDEX `images_created_at_idx` (`created_at` ASC) VISIBLE,
  CONSTRAINT `fk_images_gallery_id`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `events_backend_db`.`galleries` (`gallery_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`slots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`slots` (
  `slot_id` INT NOT NULL AUTO_INCREMENT,
  `schedule_id` INT NOT NULL,
  `stage_id` INT NOT NULL,
  `lection_id` INT NULL,
  `day` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`slot_id`),
  INDEX `fk_slots_stage_id_idx` (`stage_id` ASC) VISIBLE,
  INDEX `fk_slots_lection_id_idx` (`lection_id` ASC) VISIBLE,
  INDEX `fk_slots_schedule_id_idx` (`schedule_id` ASC) VISIBLE,
  CONSTRAINT `fk_slots_stage_id`
    FOREIGN KEY (`stage_id`)
    REFERENCES `events_backend_db`.`stages` (`stage_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_slots_lection_id`
    FOREIGN KEY (`lection_id`)
    REFERENCES `events_backend_db`.`lections` (`lection_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_slots_schedule_id`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `events_backend_db`.`schedules` (`schedule_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `events_backend_db`.`curators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`curators` (
  `curators_id` INT NOT NULL AUTO_INCREMENT,
  `titul` VARCHAR(45) NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NULL,
  `company` VARCHAR(255) NULL,
  `occupation` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `photo_url` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`curators_id`),
  INDEX `curators_created_at_idx` (`created_at` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`events_has_curators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`events_has_curators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `curator_id` INT NOT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `position` INT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_events_has_curators_curator_id_idx` (`curator_id` ASC) INVISIBLE,
  INDEX `fk_events_has_curators_event_id_idx` (`event_id` ASC) VISIBLE,
  INDEX `events_has_curators_position_idx` (`position` ASC) VISIBLE,
  INDEX `events_has_curators_created_at_idx` (`created_at` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_events_has_curators_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `events_backend_db`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_curators_curator_id`
    FOREIGN KEY (`curator_id`)
    REFERENCES `events_backend_db`.`curators` (`curators_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`events_has_sponsors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`events_has_sponsors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `sponsor_id` INT NOT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `position` INT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_events_has_sponsors_sponsor_id_idx` (`sponsor_id` ASC) VISIBLE,
  INDEX `fk_events_has_sponsors_event_id_idx` (`event_id` ASC) VISIBLE,
  INDEX `events_has_sponsors_position_idx` (`position` ASC) VISIBLE,
  INDEX `events_has_sponsors_created_at_idx` (`created_at` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_events_has_sponsors_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `events_backend_db`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_sponsors_sponsor_id`
    FOREIGN KEY (`sponsor_id`)
    REFERENCES `events_backend_db`.`sponsors` (`sponsor_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`schedules_has_stages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`schedules_has_stages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schedule_id` INT NOT NULL,
  `stage_id` INT NOT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `position` INT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_schedules_has_stages_stage_id_idx` (`stage_id` ASC) VISIBLE,
  INDEX `fk_schedules_has_stages_schedule_id_idx` (`schedule_id` ASC) VISIBLE,
  INDEX `schedules_has_stages_position_idx` (`position` ASC) VISIBLE,
  INDEX `schedules_has_stages_created_at_idx` (`created_at` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_schedules_has_stages_schedule_id`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `events_backend_db`.`schedules` (`schedule_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedules_has_stages_stage_id`
    FOREIGN KEY (`stage_id`)
    REFERENCES `events_backend_db`.`stages` (`stage_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`lections_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`lections_has_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lection_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `position` INT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_lections_has_users_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_lections_has_users_lection_id_idx` (`lection_id` ASC) VISIBLE,
  INDEX `lections_has_users_position_idx` (`position` ASC) VISIBLE,
  INDEX `lections_has_users_created_at_idx` (`position` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lections_has_users_lection_id`
    FOREIGN KEY (`lection_id`)
    REFERENCES `events_backend_db`.`lections` (`lection_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lections_has_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `events_backend_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`menu_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`menu_items` (
  `menu_item_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `title` VARCHAR(45) NOT NULL,
  `page_title` VARCHAR(255) NULL,
  `path` VARCHAR(255) NOT NULL,
  `component` VARCHAR(45) NOT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `position` INT NULL DEFAULT 1,
  `role` INT NULL DEFAULT 1,
  `is_article` TINYINT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  `is_top_menu_item` TINYINT NULL DEFAULT 1,
  `is_bottom_menu_item` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`menu_item_id`),
  INDEX `menu_items_role_position_idx` (`role` ASC, `position` ASC) VISIBLE,
  INDEX `menu_items_created_at_idx` (`created_at` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`articles` (
  `article_id` INT NOT NULL AUTO_INCREMENT,
  `menu_item_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `short_desc` VARCHAR(255) NULL,
  `desc` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`article_id`),
  INDEX `fk_articles_menu_item_id_idx` (`menu_item_id` ASC) VISIBLE,
  INDEX `articles_menu_created_at_idx` (`created_at` ASC) VISIBLE,
  CONSTRAINT `fk_articles_menu_item_id`
    FOREIGN KEY (`menu_item_id`)
    REFERENCES `events_backend_db`.`menu_items` (`menu_item_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`lections_has_speakers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`lections_has_speakers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lection_id` INT NOT NULL,
  `speaker_id` INT NOT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `position` INT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_lections_has_speakers_speaker_id_idx` (`speaker_id` ASC) VISIBLE,
  INDEX `fk_lections_has_speakers_lection_id_idx` (`lection_id` ASC) VISIBLE,
  INDEX `lections_has_speakers_position_idx` (`position` ASC) VISIBLE,
  INDEX `lections_has_speakers_created_at_idx` (`created_at` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lections_has_speakers_lection_id`
    FOREIGN KEY (`lection_id`)
    REFERENCES `events_backend_db`.`lections` (`lection_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lections_has_speakers_speaker_id`
    FOREIGN KEY (`speaker_id`)
    REFERENCES `events_backend_db`.`speakers` (`speaker_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events_backend_db`.`admin_menu_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events_backend_db`.`admin_menu_items` (
  `menu_item_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `title` VARCHAR(45) NOT NULL,
  `page_title` VARCHAR(255) NULL,
  `path` VARCHAR(255) NOT NULL,
  `component` VARCHAR(45) NOT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `position` INT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`menu_item_id`),
  INDEX `admin_menu_items_created_at_idx` (`created_at` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
